import { Meta, StoryObj } from '@storybook/react';
import { Button } from './Button';
declare const meta: Meta<typeof Button>;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Primary: Story;
export declare const PrimaryDisabled: Story;
export declare const Secondary: Story;
export declare const SecondaryDisabled: Story;
export declare const Ghost: Story;
export declare const GhostDisabled: Story;
export declare const Outline: Story;
export declare const OutlineDisabled: Story;
export declare const Link: Story;
export declare const LinkDisabled: Story;
export declare const Destructive: Story;
export declare const DestructiveDisabled: Story;
